[functions.book_ai_enrich]
verify_jwt = true

[functions.find_cover]
verify_jwt = true

[functions.smart-search]
verify_jwt = false

[functions.book_import]
verify_jwt = false

[functions.google-books-proxy]
verify_jwt = false
