-- Descriptions courtes pour les tooltips (max ~40 chars)
UPDATE badge_definitions SET description = CASE id
  WHEN 'top_contributor'       THEN 'Top 3% du mois'
  WHEN 'first_read'            THEN '1 livre lu'
  WHEN 'devourer_1'            THEN '10 livres lus'
  WHEN 'devourer_2'            THEN '25 livres lus'
  WHEN 'devourer_3'            THEN '50 livres lus'
  WHEN 'devourer_4'            THEN '100 livres lus'
  WHEN 'devourer_5'            THEN '250 livres lus'
  WHEN 'devourer_6'            THEN '500 livres lus'
  WHEN 'marathoner_1'          THEN '12 livres en un an'
  WHEN 'marathoner_2'          THEN '24 livres en un an'
  WHEN 'marathoner_3'          THEN '52 livres en un an'
  WHEN 'eclectic_1'            THEN '5 genres différents'
  WHEN 'eclectic_2'            THEN '8 genres différents'
  WHEN 'eclectic_3'            THEN '12 genres différents'
  WHEN 'long_haul'             THEN 'Un livre de 800+ pages'
  WHEN 'sprint'                THEN 'Un livre en moins de 3 jours'
  WHEN 'first_review'          THEN '1 critique écrite'
  WHEN 'reviewer_1'            THEN '5 critiques'
  WHEN 'reviewer_2'            THEN '15 critiques'
  WHEN 'reviewer_3'            THEN '50 critiques'
  WHEN 'reviewer_4'            THEN '100 critiques'
  WHEN 'reviewer_5'            THEN '250 critiques'
  WHEN 'essayist_1'            THEN '3 critiques longues'
  WHEN 'essayist_2'            THEN '10 critiques longues'
  WHEN 'essayist_3'            THEN '30 critiques longues'
  WHEN 'quoter_1'              THEN '5 citations'
  WHEN 'quoter_2'              THEN '20 citations'
  WHEN 'quoter_3'              THEN '50 citations'
  WHEN 'quoter_4'              THEN '100 citations'
  WHEN 'curator_1'             THEN '3 listes publiques'
  WHEN 'curator_2'             THEN '10 listes publiques'
  WHEN 'curator_3'             THEN '25 listes publiques'
  WHEN 'connected_1'           THEN '5 abonnements'
  WHEN 'connected_2'           THEN '20 abonnements'
  WHEN 'connected_3'           THEN '50 abonnements'
  WHEN 'influencer_1'          THEN '10 abonnés'
  WHEN 'influencer_2'          THEN '50 abonnés'
  WHEN 'influencer_3'          THEN '100 abonnés'
  WHEN 'influencer_4'          THEN '500 abonnés'
  WHEN 'appreciated_1'         THEN '10 likes reçus'
  WHEN 'appreciated_2'         THEN '50 likes reçus'
  WHEN 'appreciated_3'         THEN '200 likes reçus'
  WHEN 'appreciated_4'         THEN '1000 likes reçus'
  WHEN 'challenger'            THEN '1 défi complété'
  WHEN 'challenge_collector_1' THEN '3 défis complétés'
  WHEN 'challenge_collector_2' THEN '5 défis complétés'
  WHEN 'challenge_collector_3' THEN '10 défis complétés'
  WHEN 'nightingale'           THEN 'Palier max atteint'
  WHEN 'pioneer'               THEN 'Inscrit pendant la bêta'
  WHEN 'year_in_books'         THEN '5+ livres lus cette année'
  WHEN 'faithful'              THEN '12 mois consécutifs actif'
  WHEN 'night_owl'             THEN 'Critique postée entre 2h et 5h'
  WHEN 'first_steps'           THEN 'Onboarding complété'
  ELSE description
END;
