-- Emojis uniques par badge (colonne icon_key)
UPDATE badge_definitions SET icon_key = CASE id
  -- Lecture
  WHEN 'first_read' THEN '📖'
  WHEN 'devourer_1' THEN '🐛'
  WHEN 'devourer_2' THEN '🐛'
  WHEN 'devourer_3' THEN '🐛'
  WHEN 'devourer_4' THEN '🐛'
  WHEN 'devourer_5' THEN '🐛'
  WHEN 'devourer_6' THEN '🐛'
  WHEN 'marathoner_1' THEN '🏃'
  WHEN 'marathoner_2' THEN '🏃'
  WHEN 'marathoner_3' THEN '🏃'
  WHEN 'eclectic_1' THEN '🎨'
  WHEN 'eclectic_2' THEN '🎨'
  WHEN 'eclectic_3' THEN '🎨'
  WHEN 'long_haul' THEN '🧱'
  WHEN 'sprint' THEN '⚡'
  -- Contribution
  WHEN 'first_review' THEN '✍️'
  WHEN 'reviewer_1' THEN '🖊️'
  WHEN 'reviewer_2' THEN '🖊️'
  WHEN 'reviewer_3' THEN '🖊️'
  WHEN 'reviewer_4' THEN '🖊️'
  WHEN 'reviewer_5' THEN '🖊️'
  WHEN 'essayist_1' THEN '📜'
  WHEN 'essayist_2' THEN '📜'
  WHEN 'essayist_3' THEN '📜'
  WHEN 'quoter_1' THEN '💬'
  WHEN 'quoter_2' THEN '💬'
  WHEN 'quoter_3' THEN '💬'
  WHEN 'quoter_4' THEN '💬'
  WHEN 'curator_1' THEN '📋'
  WHEN 'curator_2' THEN '📋'
  WHEN 'curator_3' THEN '📋'
  -- Social
  WHEN 'connected_1' THEN '🤝'
  WHEN 'connected_2' THEN '🤝'
  WHEN 'connected_3' THEN '🤝'
  WHEN 'influencer_1' THEN '✨'
  WHEN 'influencer_2' THEN '✨'
  WHEN 'influencer_3' THEN '✨'
  WHEN 'influencer_4' THEN '✨'
  WHEN 'appreciated_1' THEN '💛'
  WHEN 'appreciated_2' THEN '💛'
  WHEN 'appreciated_3' THEN '💛'
  WHEN 'appreciated_4' THEN '💛'
  -- Défis
  WHEN 'challenger' THEN '🏆'
  WHEN 'challenge_collector_1' THEN '🎖️'
  WHEN 'challenge_collector_2' THEN '🎖️'
  WHEN 'challenge_collector_3' THEN '🎖️'
  WHEN 'nightingale' THEN '👑'
  -- Spécial
  WHEN 'pioneer' THEN '🚩'
  WHEN 'year_in_books' THEN '📊'
  WHEN 'faithful' THEN '🔥'
  WHEN 'night_owl' THEN '🦉'
  WHEN 'first_steps' THEN '👣'
  WHEN 'top_contributor' THEN '⭐'
  ELSE icon_key
END;
